-- Q1
SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES   E,
    DEPARTMENTS D
WHERE
        E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.LAST_NAME = 'Himuro';

-- Q2
SELECT
    E.LAST_NAME,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES   E,
    DEPARTMENTS D,
    JOBS        J
WHERE
        E.JOB_ID = J.JOB_ID
    AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND J.JOB_TITLE = 'Accountant';
    
-- Q3
SELECT
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    E.COMMISSION_PCT
FROM
    EMPLOYEES   E,
    DEPARTMENTS D
WHERE
        E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND COMMISSION_PCT IS NOT NULL;

-- Q4
SELECT
    E.LAST_NAME,
    E.SALARY,
    L.STREET_ADDRESS
FROM
    EMPLOYEES   E,
    DEPARTMENTS D,
    LOCATIONS   L
WHERE
        E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND E.SALARY <= 4000;

-- Q5
SELECT
    E1.LAST_NAME,
    E1.DEPARTMENT_ID,
    E2.LAST_NAME,
    E2.DEPARTMENT_ID
FROM
    EMPLOYEES E1,
    EMPLOYEES E2
WHERE
        E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
    AND E1.LAST_NAME = 'Chen'
    AND E1.EMPLOYEE_ID != E2.EMPLOYEE_ID;