CREATE TABLE EMP01 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

INSERT INTO EMP01 VALUES (
    NULL,
    NULL,
    'IT',
    30
);

SELECT
    *
FROM
    EMP01;

CREATE TABLE EMP02 (
    EMPNO  NUMBER NOT NULL,
    ENAME  VARCHAR2(20) NOT NULL,
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

INSERT INTO EMP02 VALUES (
    100,
    'kim',
    'IT',
    30
);

INSERT INTO EMP02 VALUES (
    100,
    'park',
    'IT',
    30
);

CREATE TABLE EMP03 (
    EMPNO  NUMBER UNIQUE,
    ENAME  VARCHAR2(20) NOT NULL,
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

INSERT INTO EMP03 VALUES (
    100,
    'kim',
    'IT',
    30
);

INSERT INTO EMP03 VALUES (
    100,
    'park',
    'IT',
    30
);

CREATE TABLE EMP04 (
    EMPNO  NUMBER PRIMARY KEY,
    ENAME  VARCHAR2(20) NOT NULL,
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

INSERT INTO EMP04 VALUES (
    100,
    'kim',
    'IT',
    30
);

INSERT INTO EMP04 VALUES (
    101,
    'park',
    'IT',
    30
);

SELECT
    *
FROM
    EMP04;

CREATE TABLE EMP05 (
    EMPNO  NUMBER PRIMARY KEY,
    ENAME  VARCHAR2(20) NOT NULL,
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
        REFERENCES DEPARTMENTS ( DEPARTMENT_ID )
);

INSERT INTO EMP05 VALUES (
    200,
    'park',
    'IT',
    3000
);

SELECT
    *
FROM
    EMP05;

CREATE TABLE EMP06 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20) NOT NULL,
    JOB    VARCHAR2(20),
    DEPTNO NUMBER,
    CONSTRAINT EMP06_EMPNO_PK PRIMARY KEY ( EMPNO ),
    CONSTRAINT EMP06_DEPTNO_FK FOREIGN KEY ( DEPTNO )
        REFERENCES DEPARTMENTS ( DEPARTMENT_ID )
);

CREATE TABLE EMP07 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

ALTER TABLE EMP07 ADD CONSTRAINT EMP07_EMPNO_PK PRIMARY KEY ( EMPNO );

ALTER TABLE EMP07
    ADD CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY ( DEPTNO )
        REFERENCES DEPARTMENTS ( DEPARTMENT_ID );

ALTER TABLE EMP07 MODIFY
    ENAME
        CONSTRAINT EMP07_ENAME_NN NOT NULL;

CREATE TABLE EMP08 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
);

ALTER TABLE EMP08 ADD (
    CONSTRAINT EMP08_EMPNO_PK PRIMARY KEY ( EMPNO ),
    CONSTRAINT EMP08_DEPTNO_FK FOREIGN KEY ( DEPTNO )
        REFERENCES DEPARTMENTS ( DEPARTMENT_ID )
) MODIFY
    ENAME
        CONSTRAINT EMP08_ENAME_NN NOT NULL;

CREATE TABLE EMP09 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER,
    GENDER CHAR(1) CHECK ( GENDER IN ( 'M', 'F' ) )
);

INSERT INTO EMP09 ( GENDER ) VALUES ( 'MM' );

CREATE TABLE EMP10 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER,
    LOC    VARCHAR2(20) DEFAULT 'Seoul'
);

SELECT
    *
FROM
    EMP10;

CREATE TABLE EMP11 (
    EMPNO  NUMBER,
    EMPTNO NUMBER,
    CONSTRAINT EMP11_EMPNO_EMPTNO_PK PRIMARY KEY ( EMPNO,
                                                   EMPTNO )
);

CREATE TABLE EMP12 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER,
    LOC    VARCHAR2(20) DEFAULT 'Seoul'
);

ALTER TABLE DEPT01 ADD CONSTRAINT DEPT01_DEPARTMENT_ID_PK PRIMARY KEY ( DEPARTMENT_ID );

ALTER TABLE EMP12
    ADD CONSTRAINT EMP_12_DEPTNO_FK FOREIGN KEY ( DEPTNO )
        REFERENCES DEPT01 ( DEPARTMENT_ID );

INSERT INTO EMP12 VALUES (
    100,
    'kim',
    'IT',
    30,
    'DD'
);

DELETE FROM DEPT01
WHERE
    DEPARTMENT_ID = 30;

DELETE FROM EMP12
WHERE
    DEPTNO = 30;

CREATE TABLE EMP13 (
    EMPNO  NUMBER,
    ENAME  VARCHAR2(20),
    JOB    VARCHAR2(20),
    DEPTNO NUMBER
        REFERENCES DEPT01 ( DEPARTMENT_ID )
            ON DELETE CASCADE
);

INSERT INTO EMP13 VALUES (
    100,
    'kim',
    'dd',
    20
);

SELECT
    *
FROM
    EMP13;

SELECT
    *
FROM
    DEPT01;

DELETE FROM DEPT01
WHERE
    DEPARTMENT_ID = 20;

--
SELECT
    EMPLOYEE_ID,
    DEPARTMENT_ID
FROM
    EMPLOYEES
WHERE
    LAST_NAME = 'King';

SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM
    DEPARTMENTS
WHERE
    DEPARTMENT_ID IN ( 80, 90 );

SELECT
    E.EMPLOYEE_ID,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME
FROM
    EMPLOYEES   E,
    DEPARTMENTS D
WHERE
        E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND LAST_NAME = 'King';